# Generated by Django 3.1.3 on 2020-11-29 11:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gymburgdorf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('gewicht', models.FloatField(default=1, verbose_name='Gewicht')),
            ],
            options={
                'verbose_name': 'Fach',
                'verbose_name_plural': 'Fächer',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teilnote', models.BooleanField(default=False, verbose_name='Teilnote')),
                ('gewicht', models.FloatField(default=1, verbose_name='Gewicht')),
                ('wert', models.FloatField(blank=True, default=1.0, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(6.0)], verbose_name='Note')),
                ('fach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noten', to='gymburgdorf.fach')),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Noten',
            },
        ),
        migrations.CreateModel(
            name='NotenManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gymburgdorf_notenmanager', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notenmanager',
                'verbose_name_plural': 'Notanmanager',
            },
        ),
        migrations.CreateModel(
            name='Teilnote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beschreibung', models.CharField(max_length=50, verbose_name='beschreibung')),
                ('gewicht', models.FloatField(default=1, verbose_name='Gewicht')),
                ('wert', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(6.0)], verbose_name='Note')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teilnoten', to='gymburgdorf.note')),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester', to='gymburgdorf.notenmanager')),
            ],
            options={
                'verbose_name': 'Semester',
                'verbose_name_plural': 'Semester',
            },
        ),
        migrations.AddField(
            model_name='fach',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faecher', to='gymburgdorf.semester'),
        ),
    ]
