# Generated by Django 3.1.3 on 2020-11-29 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymburgdorf', '0003_auto_20201129_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='beschreibung',
        ),
        migrations.RemoveField(
            model_name='teilnote',
            name='beschreibung',
        ),
        migrations.AddField(
            model_name='note',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='teilnote',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='fach',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='Name'),
        ),
    ]
