# Generated by Django 3.1.3 on 2020-12-11 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymburgdorf', '0005_auto_20201211_1412'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='teilnote',
            new_name='is_partial_grade',
        ),
        migrations.AlterField(
            model_name='note',
            name='is_partial_grade',
            field=models.BooleanField(default=False, verbose_name='Teilnote?'),
        ),
        migrations.RenameField(
            model_name='note',
            old_name='gewicht',
            new_name='weight',
        ),
        migrations.RenameField(
            model_name='teilnote',
            old_name='gewicht',
            new_name='weight',
        ),
        migrations.RenameField(
            model_name='fach',
            old_name='gewicht',
            new_name='weight',
        ),
    ]
