# Generated by Django 3.1.3 on 2020-12-11 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymburgdorf', '0006_auto_20201211_1421'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='wert',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='teilnote',
            old_name='wert',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='semester',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='fach',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='teilnote',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='teilnote',
            old_name='note',
            new_name='grade',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='fach',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='fach',
            old_name='semester',
            new_name='semester',
        ),
        migrations.RenameField(
            model_name='semester',
            old_name='manager',
            new_name='manager',
        ),
    ]
    
