# Generated by Django 3.1.3 on 2020-12-11 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gymburgdorf', '0007_auto_20201211_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fach',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='gymburgdorf.semester'),
        ),
        migrations.AlterField(
            model_name='note',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='gymburgdorf.fach'),
        ),
        migrations.AlterField(
            model_name='teilnote',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partial_grades', to='gymburgdorf.note'),
        ),
    ]
