# Generated by Django 3.1.3 on 2020-12-12 17:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymburgdorf', '0009_auto_20201212_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='saved_value',
            field=models.FloatField(default=None, null=True, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(6.0)], verbose_name='Notenwert'),
        ),
        migrations.AlterField(
            model_name='note',
            name='value',
            field=models.FloatField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(6.0)], verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='teilnote',
            name='value',
            field=models.FloatField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(6.0)], verbose_name='Note'),
        ),
    ]
