# Generated by Django 3.1.3 on 2020-12-17 19:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gymburgdorf', '0010_auto_20201212_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='fach',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Erstellt am'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fach',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Geändert am'),
        ),
        migrations.AddField(
            model_name='info',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Erstellt am'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='info',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Geändert am'),
        ),
        migrations.AddField(
            model_name='note',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Erstellt am'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='note',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Geändert am'),
        ),
        migrations.AddField(
            model_name='notenmanager',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Erstellt am'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notenmanager',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Geändert am'),
        ),
        migrations.AddField(
            model_name='semester',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Erstellt am'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='semester',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Geändert am'),
        ),
        migrations.AddField(
            model_name='teilnote',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Erstellt am'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teilnote',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Geändert am'),
        ),
    ]
