# Generated by Django 3.2.1 on 2021-05-06 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gymburgdorf', '0011_auto_20201217_2012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spruch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Inhalt')),
                ('von', models.CharField(max_length=250, verbose_name='Von')),
                ('datum', models.DateField(verbose_name='Datum')),
                ('bemerkungen', models.TextField(verbose_name='Bemerkungen')),
                ('published', models.BooleanField(default=False, verbose_name='Veröffentlicht?')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Veröffentlicht um')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gymburgdorf_sprueche', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
