# Generated by Django 3.2.1 on 2021-05-07 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gymburgdorf', '0013_alter_spruch_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=50, verbose_name='Titel')),
                ('beschreibung', models.TextField(verbose_name='Beschreibung')),
                ('personen', models.CharField(max_length=250, verbose_name='Personen')),
                ('kategorie', models.CharField(choices=[('quote', 'Zitat'), ('giftidea', 'Geschenkidee')], max_length=20, verbose_name='Kategorie')),
                ('published', models.BooleanField(default=False, verbose_name='Veröffentlicht?')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Veröffentlicht um')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gymburgdorf_sprueche', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Benutzerinhalt',
                'verbose_name_plural': 'Benutzerinhalte',
            },
        ),
        migrations.DeleteModel(
            name='Spruch',
        ),
    ]
