# Generated by Django 3.2.1 on 2021-05-07 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymburgdorf', '0014_auto_20210507_1907'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercontent',
            options={'default_permissions': ('change', 'publish', 'delete'), 'verbose_name': 'Benutzerinhalt', 'verbose_name_plural': 'Benutzerinhalte'},
        ),
    ]
