# Generated by Django 3.2.10 on 2022-06-03 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymburgdorf', '0016_maturabookselection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maturabookselection',
            options={'verbose_name': 'Maturbuchreservation', 'verbose_name_plural': 'Maturbuchreservationen'},
        ),
    ]
