# Generated by Django 3.2.10 on 2022-07-24 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymburgdorf', '0017_alter_maturabookselection_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='maturabookselection',
            name='is_removed',
            field=models.BooleanField(default=False, verbose_name='Gelöscht'),
        ),
        migrations.AddField(
            model_name='maturabookselection',
            name='typ',
            field=models.CharField(choices=[('reserved', 'reserviert'), ('presaved', 'vorgemerkt')], default='presaved', max_length=50, verbose_name='Typ'),
        ),
        migrations.AddField(
            model_name='maturabookselection',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
