# Generated by Django 4.1 on 2022-08-15 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gymburgdorf', '0018_auto_20220724_2356'),
    ]

    operations = [
        migrations.CreateModel(
            name='MulusCollectionPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=25)),
                ('first_name', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'MULUS-Sammlung: Person',
                'verbose_name_plural': 'MULUS-Sammlung: Personen',
            },
        ),
        migrations.CreateModel(
            name='MulusCollectionPersonQuoteRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymburgdorf.muluscollectionperson')),
            ],
            options={
                'verbose_name': 'MULUS-Sammlung: Zitat-Person-Verbindung',
                'verbose_name_plural': 'MULUS-Sammlung: Zitat-Person-Verbindungen',
            },
        ),
        migrations.CreateModel(
            name='MulusCollectionQuote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('people', models.ManyToManyField(through='gymburgdorf.MulusCollectionPersonQuoteRelation', to='gymburgdorf.muluscollectionperson')),
            ],
            options={
                'verbose_name': 'MULUS-Sammlung: Zitat',
                'verbose_name_plural': 'MULUS-Sammlung: Zitate',
            },
        ),
        migrations.AddField(
            model_name='muluscollectionpersonquoterelation',
            name='quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymburgdorf.muluscollectionquote'),
        ),
        migrations.AddField(
            model_name='muluscollectionperson',
            name='quotes',
            field=models.ManyToManyField(through='gymburgdorf.MulusCollectionPersonQuoteRelation', to='gymburgdorf.muluscollectionquote'),
        ),
    ]
