# Generated by Django 3.2.10 on 2022-08-29 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gymburgdorf', '0019_muluscollectionperson_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MulusCollectionQuoteReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(default=True)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymburgdorf.muluscollectionquote')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MULUS-Sammlung: Zitat-Bewertung',
                'verbose_name_plural': 'MULUS-Sammlung: Zitat-Bewertungen',
            },
        ),
    ]
