# Generated by Django 3.2.10 on 2022-08-29 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gymburgdorf', '0020_muluscollectionquotereview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muluscollectionquotereview',
            name='quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='gymburgdorf.muluscollectionquote'),
        ),
        migrations.AlterField(
            model_name='muluscollectionquotereview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gymburgdorf_muluscollection_quotereviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
